# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1249da1fb122b593f36b32f4b009c1a7d903652e2c26ce54a1cd6ea100ed46d2ec7452bd378babf6ec4d156ea62e8ca0407a511fe56a37d18c13fbdae618180

test:
  secret_key_base: 90ec110bc2aa7b0a600d91092b44962d7fcfe85e0d9586ec4b8880be8eed483ebaff19d04582d5f311c5469fdb7063b03d7c9c7c77eb35c612d3c88211e05def

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
